### PR TITLE
Create data_exploration.ipynb for answering similarity question

### PR DESCRIPTION
**Pull request by tedim52**
-Added a data_exploration.ipynb where I conducted initial data analysis on the attribute dataset
-In order to answer the question: What attributes are indicative of similar Googlers? I isolated for several Googlers that had the same manager and compared how similar their other attributes were
-Conclusion: Manager attribute is indicative of similar Googler's as many Googler's with the same manager had identical values for other attributes

### CODE REVIEW

**Review by meritus — APPROVED** [review]

**Comment by tedim52** [comment]
MERGED tedi, kayla, dean branches and resolved all conflicts

Major updates:
-Create utilities/ folder to contain all data analysis scripts
-Move data folder outside of remote and local repository
-Create Googler and Google classes and main.py
-Add .gitignore folder to prevent .ipynb checkpoints folder and __pycache__ folders from being committed to local repository

**Comment by tedim52** [comment]
--- once merged with master we should all be good to pull onto VM instances.

**Review by kpatterson01 — DISMISSED** [review]
LGTM! Thanks Tedi for merging all of our branches together to have a standard local repo! Great job :)

**Review by kpatterson01 — APPROVED** [review]
LGTM! Thanks Tedi for merging all of our branches together to have a standard local repo! Great job :)

**Pull request merged**
